apiVersion: v1
kind: Service
metadata:
  name: trips-service
  labels:
    app: trips-service
spec:
  type: ClusterIP
  selector:
    app: trips-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http